Repository src-d/lookout, pull requests merged in 2018-12, with the labels that each got.

#378 Use go-cli lib
  Gopkg.lock
  cmd/dummy/main.go
  cmd/lookout-sdk/event.go
  cmd/lookout-sdk/main.go
  cmd/lookout-sdk/push.go
  cmd/lookout-sdk/review.go
  cmd/lookout-sdk/version.go
  cmd/lookoutd/common.go
  cmd/lookoutd/main.go
  cmd/lookoutd/migrate.go
  cmd/lookoutd/serve.go
  cmd/lookoutd/version.go
  cmd/lookoutd/watch.go
  cmd/lookoutd/work.go
  util/cli/app.go
  util/cli/common_options.go
  util/cli/log.go
  vendor/gopkg.in/src-d/go-cli.v0/LICENSE
  vendor/gopkg.in/src-d/go-cli.v0/addcommand.go
  vendor/gopkg.in/src-d/go-cli.v0/cli.go
  vendor/gopkg.in/src-d/go-cli.v0/context.go
  vendor/gopkg.in/src-d/go-cli.v0/doc.go
  vendor/gopkg.in/src-d/go-cli.v0/log.go
  vendor/gopkg.in/src-d/go-cli.v0/pprof.go
  vendor/gopkg.in/src-d/go-cli.v0/profiler.go
  vendor/gopkg.in/src-d/go-cli.v0/version.go
Labels: enhancement

#405 Set defaults for GITHUB_USER and GITHUB_TOKEN
  docker-compose.yml
Labels: empathy-sessions, enhancement

#410 Change default repo in config-template. Setting a placeholder
  config.yml.tpl
Labels: enhancement

#398 Enhance docs with GitBook
  .gitbook.yaml
  .github/CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DCO
  LICENSE.md
  Makefile
  NOTICE.md
  README.md
  config.yml.tpl
  docker-compose-rabbitmq.yml
  docker-compose.yml
  docs/CONTRIBUTING.md
  docs/README.md
  docs/analyzers-creation.md
  docs/analyzers-examples.md
  docs/analyzers.md
  docs/architecture.md
  docs/assets/lookout-sdk-seq-diagram.md
  docs/assets/lookout-sdk-seq-diagram.png
  docs/assets/lookout-sdk-seq-diagram.svg
  docs/assets/lookout-seq-diagram.md
  docs/assets/lookout-seq-diagram.png
  docs/assets/lookout-seq-diagram.svg
  docs/assets/sourced.png
  docs/configuration.md
  docs/distributed.md
  docs/how-to-run.md
  docs/lookout-sdk.md
  docs/lookout-seq-diagram.md
  docs/lookout-seq-diagram.svg
  sdk/LICENSE
  sdk/README.md
  sdk/seq-diagram.svg
Labels: enhancement

#424 Naming lookout
  README.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/analyzers-creation.md
  docs/analyzers.md
  docs/architecture.md
  docs/configuration.md
  docs/how-to-run.md
  docs/lookout-sdk.md
Labels: bug

#423 Enhance docs (v2)
  README.md
  docs/CONTRIBUTING.md
  docs/analyzers-examples.md
  docs/architecture.md
  docs/how-to-run.md
  docs/lookout-sdk.md
Labels: enhancement
