Repository src-d/lookout, pull requests merged in 2019-01, with the labels that each got.

#473 Fix callback test
  web/auth_test.go
Labels: enhance-tests

#471 Use log wrapper instead of console.error directly
  frontend/src/services/auth.ts
  frontend/src/services/log.test.tsx
  frontend/src/services/log.ts
Labels: enhancement, web-ui

#476 New header without HTML and with proper product logo
  README.md
  docs/assets/sourced-lookout.png
Labels: documentation, enhancement

#474 Let web-start work without assets
  Makefile.web
  docs/CONTRIBUTING.md
  docs/web.md
Labels: documentation, enhancement

#488 Logs enhancement
  provider/github/client.go
  provider/github/client_test.go
  provider/github/poster.go
  provider/github/review.go
  provider/github/watcher.go
Labels: enhancement

#497 Update docker-compose command
  docs/lookout-sdk.md
Labels: documentation, enhancement
